apiVersion: apps/v1
kind: Deployment

metadata:
  name: devopspractice-web
  namespace: devopspractice

spec:
  replicas: 1

  selector:
    matchLabels:
      app: devopspractice-web

  template:
    metadata:
      labels:
        app: devopspractice-web

    spec:
      containers:
      - name: devopspractice-web

        image: abdulghaffar2455/devopspractice:4374d20aaa406ba4d5052586d9cad0ac2cd55b3a

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        # env:
        # # - name: ConnectionStrings__DefaultConnection
        # #   value: "Server=sqlserver;Database=DevOpsPractice;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True"
        # env:
        #   - name: ConnectionStrings__DefaultConnection
        #     valueFrom:
        #       secretKeyRef:
        #         name: sql-secret
        #         key: ConnectionStrings__DefaultConnection
        envFrom:
          - configMapRef:
              name: app-config

          - secretRef:
              name: sql-secret

        startupProbe:
          httpGet:
            path: /health
            port: 8080

          failureThreshold: 60
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /health
            port: 8080

          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 8080

          initialDelaySeconds: 20
          periodSeconds: 20
