apiVersion: v1
kind: ConfigMap

metadata:
  name: app-config
  namespace: devopspractice

data:

  ASPNETCORE_ENVIRONMENT: "Development"

  Logging__LogLevel__Default: "Information"

  Logging__LogLevel__Microsoft.AspNetCore: "Warning"