apiVersion: v1
kind: Secret

# metadata:
#   name: sql-secret
#   namespace: devopspractice

metadata:
  name: sql-secret
  namespace: devopspractice
  annotations:
    argocd.argoproj.io/sync-options: Prune=false

type: Opaque

stringData:

  MSSQL_SA_PASSWORD: YourStrong@Passw0rd
  ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=DevOpsPractice;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True"