apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devopspractice

data:
  ASPNETCORE_ENVIRONMENT: Production
  Logging__LogLevel__Default: Warning
  Logging__LogLevel__Microsoft.AspNetCore: Warning