apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-configmap.yaml
  - app-deployment.yaml
  - app-hpa.yaml
  - app-service.yaml
  - ingress.yaml
  - sql-deployment.yaml
  - sql-pvc.yaml
  - sql-service.yaml